### PR TITLE
Implement ProgressiveRotateStrategy

### PR DESCRIPTION
**Pull request by kachkaev**
See #7 

I used the following hacks in config.yml:

``` yml
services:
    my_destination:
        class: Zenstruck\Backup\Destination\RotatedDestination
        arguments: ["@my_destination_child", "@my_destination_strategy"]
        tags:
            - { name: zenstruck_backup.destination }

    my_destination_child:
        class: Zenstruck\Backup\Destination\StreamDestination
        arguments: [sample_destination, "%backup_root_dir%/%backup_relative_dir%"]

    my_destination_strategy:
        class: Zenstruck\Backup\RotateStrategy\ProgressiveRotateStrategy
        arguments:
            - "@my_progressive_rotate_rule_collection"

    my_progressive_rotate_rule_collection:
        class: Zenstruck\Backup\RotateStrategy\ProgressiveRotateRuleCollection
        factory_class: Zenstruck\Backup\RotateStrategy\ProgressiveRotateRuleCollection
        factory_method: createFromArray
        arguments:
            -
                -
                    frequency: all
                    max_age:   5 minutes
                -
                    frequency: 10 minutes
                    max_age:   1 hour
                -
                    frequency: 1 hour
                    max_age:   1 day
                -
                    frequency: 1 day
                    max_age:   14 days
                -
                    frequency: 1 week
                    max_age:   6 weeks
                -
                    frequency: 1 month
```

### CODE REVIEW

**Comment by kbond** [comment]
Awesome @kachkaev, thanks for this. Wow, this is complicated! I definitely want to get this unit tested. If you don't have time, that's fine, I can try my hand it doing it.

I will review it fully but I think I need some more clarification on your use case. With the above config, how often are you running the backup command? Every 5 minutes?

**Comment by kachkaev** [comment]
Once in 10 minutes. If you call the command manually at a higher frequency, all backups ‘younger’ than five minutes get preserved (here is what the first rule is for).

I'm wondering if it is possible to improve `$backup->getCreatedAt()` in some way. Currently the result completely relies on the time reported by the OS. This may not work, for example, after I replaced the server and restored the backups from another place. The first call of `zenstruck:backup` then will keep only a single archive out of all that have been copied. This is because their creation date will actually be the same.

Maybe using the filename itself will help here, but I can't come up with some general solution in my head.

**UPD:** I created a separate issue of this, see #9.

**Comment by kbond** [comment]
Ok, let me review and add some tests.

For the `$backup->getCreatedAt()`, what about a `FilenameTimestampDestination` wrapper that builds the `Backup`'s using the filename for the createdAt? A constructor option could be a regex to be used to extract the timestamp from the filename?

**Comment by kachkaev** [comment]
Yeah, I guess that's the direction in which the solution is. Maybe it is even possible to use the backup namer as a source for that regexp. Prefix and timestamp format are there already.

**Comment by kachkaev** [comment]
Hey @kbond,

Any updates on this one?

**Comment by kbond** [comment]
Hey @kachkaev, I haven't forgot about this but am pretty busy at the moment... In the meantime, have you looked at this fork? https://github.com/RunOpenCode/backup - I believe it has a rotating backup system.

**Comment by kachkaev** [comment]
Cool! Thanks for the link to that repo and also let the author know about this PR. No worries about this delay – I'm not in a need to use the code in any new project at the moment. Just think that it might be useful in future at some point.

**Comment by kachkaev** [comment]
Shall we close this PR as stale?

**Comment by kbond** [comment]
Sure. I'd like to revisit this library this year.

**Pull request closed without merging**
